export const Bounce: any;
export const Fade: any;
export const Flip: any;
export const LightSpeed: any;
export const Reveal: any;
export const Roll: any;
export const Rotate: any;
export const Slide: any;
export const Zoom: any;
export default _default;
export const _default: any;
